/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'creator',
    path: '/creator',
    component: 'layout.base',
    meta: {
      title: 'creator'
    },
    children: [
      {
        name: 'creator_approval',
        path: '/creator/approval',
        component: 'view.creator_approval',
        meta: {
          title: 'creator_approval'
        }
      },
      {
        name: 'creator_publish-management',
        path: '/creator/publish-management',
        component: 'view.creator_publish-management',
        meta: {
          title: 'creator_publish-management'
        }
      },
      {
        name: 'creator_work',
        path: '/creator/work',
        component: 'view.creator_work',
        meta: {
          title: 'creator_work'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      constant: true,
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'monitor',
    path: '/monitor',
    component: 'layout.base',
    meta: {
      title: 'monitor',
      i18nKey: 'route.monitor'
    },
    children: [
      {
        name: 'monitor_cache',
        path: '/monitor/cache',
        component: 'view.monitor_cache',
        meta: {
          title: 'monitor_cache',
          i18nKey: 'route.monitor_cache'
        },
        children: [
          {
            name: 'monitor_cache_list',
            path: '/monitor/cache/list',
            component: 'view.monitor_cache_list',
            meta: {
              title: 'monitor_cache_list',
              i18nKey: 'route.monitor_cache_list'
            }
          }
        ]
      },
      {
        name: 'monitor_job',
        path: '/monitor/job',
        component: 'view.monitor_job',
        meta: {
          title: 'monitor_job',
          i18nKey: 'route.monitor_job'
        }
      },
      {
        name: 'monitor_job-log',
        path: '/monitor/job-log',
        component: 'view.monitor_job-log',
        meta: {
          title: 'monitor_job-log',
          i18nKey: 'route.monitor_job-log'
        }
      },
      {
        name: 'monitor_logininfor',
        path: '/monitor/logininfor',
        component: 'view.monitor_logininfor',
        meta: {
          title: 'monitor_logininfor',
          i18nKey: 'route.monitor_logininfor'
        }
      },
      {
        name: 'monitor_online',
        path: '/monitor/online',
        component: 'view.monitor_online',
        meta: {
          title: 'monitor_online',
          i18nKey: 'route.monitor_online'
        }
      },
      {
        name: 'monitor_operlog',
        path: '/monitor/operlog',
        component: 'view.monitor_operlog',
        meta: {
          title: 'monitor_operlog',
          i18nKey: 'route.monitor_operlog'
        }
      },
      {
        name: 'monitor_server',
        path: '/monitor/server',
        component: 'view.monitor_server',
        meta: {
          title: 'monitor_server',
          i18nKey: 'route.monitor_server'
        }
      }
    ]
  },
  {
    name: 'social-callback',
    path: '/social-callback',
    component: 'layout.blank$view.social-callback',
    meta: {
      title: 'social-callback',
      i18nKey: 'route.social-callback',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      localIcon: 'menu-system',
      order: 1
    },
    children: [
      {
        name: 'system_client',
        path: '/system/client',
        component: 'view.system_client',
        meta: {
          title: 'system_client',
          i18nKey: 'route.system_client'
        }
      },
      {
        name: 'system_config',
        path: '/system/config',
        component: 'view.system_config',
        meta: {
          title: 'system_config',
          i18nKey: 'route.system_config'
        }
      },
      {
        name: 'system_dept',
        path: '/system/dept',
        component: 'view.system_dept',
        meta: {
          title: 'system_dept',
          i18nKey: 'route.system_dept'
        }
      },
      {
        name: 'system_dict',
        path: '/system/dict',
        component: 'view.system_dict',
        meta: {
          title: 'system_dict',
          i18nKey: 'route.system_dict'
        }
      },
      {
        name: 'system_file-manager',
        path: '/system/file-manager',
        component: 'view.system_file-manager',
        meta: {
          title: 'system_file-manager',
          i18nKey: 'route.system_file-manager'
        }
      },
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu',
          localIcon: 'menu-tree-table',
          order: 3
        }
      },
      {
        name: 'system_notice',
        path: '/system/notice',
        component: 'view.system_notice',
        meta: {
          title: 'system_notice',
          i18nKey: 'route.system_notice'
        }
      },
      {
        name: 'system_notify',
        path: '/system/notify',
        meta: {
          title: 'system_notify',
          i18nKey: 'route.system_notify'
        },
        children: [
          {
            name: 'system_notify_message',
            path: '/system/notify/message',
            component: 'view.system_notify_message',
            meta: {
              title: 'system_notify_message',
              i18nKey: 'route.system_notify_message'
            }
          },
          {
            name: 'system_notify_template',
            path: '/system/notify/template',
            component: 'view.system_notify_template',
            meta: {
              title: 'system_notify_template',
              i18nKey: 'route.system_notify_template'
            }
          }
        ]
      },
      {
        name: 'system_oss',
        path: '/system/oss',
        component: 'view.system_oss',
        meta: {
          title: 'system_oss',
          i18nKey: 'route.system_oss'
        }
      },
      {
        name: 'system_oss-config',
        path: '/system/oss-config',
        component: 'view.system_oss-config',
        meta: {
          title: 'system_oss-config',
          i18nKey: 'route.system_oss-config',
          constant: true,
          hideInMenu: true,
          icon: 'hugeicons:configuration-01'
        }
      },
      {
        name: 'system_post',
        path: '/system/post',
        component: 'view.system_post',
        meta: {
          title: 'system_post',
          i18nKey: 'route.system_post'
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role'
        }
      },
      {
        name: 'system_sms',
        path: '/system/sms',
        meta: {
          title: 'system_sms',
          i18nKey: 'route.system_sms'
        },
        children: [
          {
            name: 'system_sms_channel',
            path: '/system/sms/channel',
            component: 'view.system_sms_channel',
            meta: {
              title: 'system_sms_channel',
              i18nKey: 'route.system_sms_channel'
            }
          },
          {
            name: 'system_sms_log',
            path: '/system/sms/log',
            component: 'view.system_sms_log',
            meta: {
              title: 'system_sms_log',
              i18nKey: 'route.system_sms_log'
            }
          },
          {
            name: 'system_sms_template',
            path: '/system/sms/template',
            component: 'view.system_sms_template',
            meta: {
              title: 'system_sms_template',
              i18nKey: 'route.system_sms_template'
            }
          }
        ]
      },
      {
        name: 'system_tenant',
        path: '/system/tenant',
        component: 'view.system_tenant',
        meta: {
          title: 'system_tenant',
          i18nKey: 'route.system_tenant'
        }
      },
      {
        name: 'system_tenant-audit',
        path: '/system/tenant-audit',
        component: 'view.system_tenant-audit',
        meta: {
          title: 'system_tenant-audit',
          i18nKey: 'route.system_tenant-audit'
        }
      },
      {
        name: 'system_tenant-dashboard',
        path: '/system/tenant-dashboard',
        component: 'view.system_tenant-dashboard',
        meta: {
          title: 'system_tenant-dashboard',
          i18nKey: 'route.system_tenant-dashboard'
        }
      },
      {
        name: 'system_tenant-package',
        path: '/system/tenant-package',
        component: 'view.system_tenant-package',
        meta: {
          title: 'system_tenant-package',
          i18nKey: 'route.system_tenant-package'
        }
      },
      {
        name: 'system_tenant-quota',
        path: '/system/tenant-quota',
        component: 'view.system_tenant-quota',
        meta: {
          title: 'system_tenant-quota',
          i18nKey: 'route.system_tenant-quota'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user'
        }
      }
    ]
  },
  {
    name: 'tool',
    path: '/tool',
    component: 'layout.base',
    meta: {
      title: 'tool',
      i18nKey: 'route.tool',
      localIcon: 'menu-tool',
      order: 4
    },
    children: [
      {
        name: 'tool_build',
        path: '/tool/build',
        component: 'view.tool_build',
        meta: {
          title: 'tool_build',
          i18nKey: 'route.tool_build'
        }
      },
      {
        name: 'tool_gen',
        path: '/tool/gen',
        meta: {
          title: 'tool_gen',
          i18nKey: 'route.tool_gen',
          localIcon: 'menu-code',
          order: 2
        },
        children: [
          {
            name: 'tool_gen_datasource',
            path: '/tool/gen/datasource',
            component: 'view.tool_gen_datasource',
            meta: {
              title: 'tool_gen_datasource',
              i18nKey: 'route.tool_gen_datasource',
              icon: 'mdi:database-cog-outline',
              order: 1
            }
          },
          {
            name: 'tool_gen_history',
            path: '/tool/gen/history',
            component: 'view.tool_gen_history',
            meta: {
              title: 'tool_gen_history',
              i18nKey: 'route.tool_gen_history',
              icon: 'mdi:history',
              order: 3
            }
          },
          {
            name: 'tool_gen_template',
            path: '/tool/gen/template',
            component: 'view.tool_gen_template',
            meta: {
              title: 'tool_gen_template',
              i18nKey: 'route.tool_gen_template',
              icon: 'mdi:file-document-edit-outline',
              order: 2
            }
          }
        ]
      },
      {
        name: 'tool_swagger',
        path: '/tool/swagger',
        component: 'view.tool_swagger',
        meta: {
          title: 'tool_swagger',
          i18nKey: 'route.tool_swagger'
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      icon: 'material-symbols:account-circle-full',
      hideInMenu: true
    }
  }
];
